export const BUILT_IN_IMAGES = [
  { name: 'image_1', src: 'https://picsum.photos/seed/scenery1/800/600' },
  { name: 'image_2', src: 'https://picsum.photos/seed/scenery2/800/600' },
  { name: 'image_3', src: 'https://picsum.photos/seed/scenery3/800/600' },
  { name: 'image_4', src: 'https://picsum.photos/seed/scenery4/800/600' },
  { name: 'image_5', src: 'https://picsum.photos/seed/scenery5/800/600' },
  { name: 'image_6', src: 'https://picsum.photos/seed/scenery6/800/600' },
  { name: 'image_7', src: 'https://picsum.photos/seed/scenery7/800/600' },
  { name: 'image_8', src: 'https://picsum.photos/seed/scenery8/800/600' },
  { name: 'image_9', src: 'https://picsum.photos/seed/scenery9/800/600' },
  { name: 'image_10', src: 'https://picsum.photos/seed/scenery10/800/600' },
];

export const TRANSLATIONS = {
  en: {
    title: 'Jigsaw Puzzle World',
    selectImage: 'Step 1: Select an Image',
    builtInImages: 'Built-in Images',
    uploadYourOwn: 'Or Upload Your Own',
    uploadButton: 'Choose Image',
    gameOptions: 'Step 2: Game Options',
    gameMode: 'Game Mode',
    traditional: 'Traditional Jigsaw',
    sliding: 'Sliding Puzzle',
    difficulty: 'Difficulty',
    timer: 'Timer',
    enableTimer: 'Enable Timer',
    startGame: 'Start Game',
    pieces: 'pieces',
    playAgain: 'Play Again',
    congratulations: 'Congratulations!',
    puzzleCompleted: 'You have successfully completed the puzzle.',
    gamePaused: 'Game Paused',
    resumeGame: 'Press the play button on the timer to resume.',
    incorrectPlacement: 'This piece does not belong here.',
    selectAPiece: 'Select a piece from the tray below.',
    placeThePiece: 'Click on the corresponding number on the board to place it.',
    time: 'Time',
    pause: 'Pause',
    resume: 'Resume',
    image_1: 'Image 1',
    image_2: 'Image 2',
    image_3: 'Image 3',
    image_4: 'Image 4',
    image_5: 'Image 5',
    image_6: 'Image 6',
    image_7: 'Image 7',
    image_8: 'Image 8',
    image_9: 'Image 9',
    image_10: 'Image 10',
  },
  zh: {
    title: '拼圖遊戲世界',
    selectImage: '第一步：選擇圖片',
    builtInImages: '內建圖片',
    uploadYourOwn: '或上傳您自己的圖片',
    uploadButton: '選擇圖片',
    gameOptions: '第二步：遊戲選項',
    gameMode: '遊戲類型',
    traditional: '傳統拼圖',
    sliding: '滑塊拼圖',
    difficulty: '難度',
    timer: '計時器',
    enableTimer: '啟用計時器',
    startGame: '開始遊戲',
    pieces: '片',
    playAgain: '再玩一次',
    congratulations: '恭喜！',
    puzzleCompleted: '您已成功完成拼圖。',
    gamePaused: '遊戲暫停',
    resumeGame: '按下計時器上的播放按鈕以繼續遊戲。',
    incorrectPlacement: '這片拼圖不屬於這裡。',
    selectAPiece: '從下方的拼圖盤中選擇一片拼圖。',
    placeThePiece: '點擊板上對應的編號以放置它。',
    time: '時間',
    pause: '暫停',
    resume: '繼續',
    image_1: '圖片 1',
    image_2: '圖片 2',
    image_3: '圖片 3',
    image_4: '圖片 4',
    image_5: '圖片 5',
    image_6: '圖片 6',
    image_7: '圖片 7',
    image_8: '圖片 8',
    image_9: '圖片 9',
    image_10: '圖片 10',
  },
};